services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - 5000:5000
    env_file:
      - ./.env
    # command: sh -c "npx prisma db push && npm run start:dev"
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
