services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SYNCHRONIZE=false
      - RUN_MIGRATIONS=${RUN_MIGRATIONS}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
volumes:
  postgres:
